spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
      #     filters:
      #       - name: RequestRateLimiter
      #         args:
      #           redis-rate-limiter.replenishRate: 10
      #           redis-rate-limiter.burstCapacity: 20
      # default-filters:
      #   - name: CircuitBreaker
      #     args:
      #       name: defaultCircuitBreaker
      #       fallbackUri: forward:/fallback
eureka:
  instance:
    hostname: localhost
