spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
  tracing:
    sampling:
      probability: 1.0 # 開發環境可以設置為1.0，生產環境建議設置較小的值
    propagation:
      type: w3c
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.example.security: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  instance:
    hostname: localhost

jwt:
  secret: U2VjdXJlUmFuZG9tU2VjcmV0S2V5Rm9yU3ByaW5nQ2xvdWRHYXRld2F5
