spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
server:
  port: 8082
