spring:
  #   datasource:
  #     url: jdbc:mysql://localhost:3306/product_db_dev
  #     username: root
  #     password: root
  tracing:
    sampling:
      probability: 1.0 # 開發環境可以設置為1.0，生產環境建議設置較小的值
    propagation:
      type: w3c
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
