server:
  port: 8888

spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joe830507/spring-cloud-impl
          username: joe830507
          password: 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
          search-paths: config
          default-label: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
