server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joe830507/spring-cloud-impl
          search-paths: config
          default-label: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
